// Generated by Classiq.
// Classiq version: 0.50.0
// Creation timestamp: 2024-09-26T04:30:52.483829+00:00
// Random seed: 2855359401

OPENQASM 2.0;
include "qelib1.inc";
gate main_identity q0,q1,q2,q3 {
}

gate apply_to_all_expanded___4 q0,q1,q2,q3 {
  h q0;
  h q1;
  h q2;
  h q3;
}

gate main_hadamard_transform q0,q1,q2,q3 {
  apply_to_all_expanded___4 q0,q1,q2,q3;
}

gate mcphase(param0) q0,q1,q2 {
  cp(pi/2) q1,q2;
  cx q1,q0;
  cp(-pi/2) q0,q2;
  cx q1,q0;
  cp(pi/2) q0,q2;
}

gate mcphase_140054432585424(param0) q0,q1,q2 {
  cp(pi/4) q1,q2;
  cx q1,q0;
  cp(-pi/4) q0,q2;
  cx q1,q0;
  cp(pi/4) q0,q2;
}

gate mcphase_140054432591248(param0) q0,q1,q2 {
  cp(pi/8) q1,q2;
  cx q1,q0;
  cp(-pi/8) q0,q2;
  cx q1,q0;
  cp(pi/8) q0,q2;
}

gate mcphase_140054432581584(param0) q0,q1,q2 {
  cp(pi/16) q1,q2;
  cx q1,q0;
  cp(-pi/16) q0,q2;
  cx q1,q0;
  cp(pi/16) q0,q2;
}

gate mcphase_140054432587792(param0) q0,q1,q2 {
  cp(pi/32) q1,q2;
  cx q1,q0;
  cp(-pi/32) q0,q2;
  cx q1,q0;
  cp(pi/32) q0,q2;
}

gate mcphase_140054432590928(param0) q0,q1,q2 {
  cp(pi/64) q1,q2;
  cx q1,q0;
  cp(-pi/64) q0,q2;
  cx q1,q0;
  cp(pi/64) q0,q2;
}

gate mcphase_140054432590736(param0) q0,q1,q2 {
  cp(pi/4) q1,q2;
  cx q1,q0;
  cp(-pi/4) q0,q2;
  cx q1,q0;
  cp(pi/4) q0,q2;
}

gate mcphase_140054432590160(param0) q0,q1,q2 {
  cp(pi/8) q1,q2;
  cx q1,q0;
  cp(-pi/8) q0,q2;
  cx q1,q0;
  cp(pi/8) q0,q2;
}

gate mcphase_140054432585488(param0) q0,q1,q2 {
  cp(pi/16) q1,q2;
  cx q1,q0;
  cp(-pi/16) q0,q2;
  cx q1,q0;
  cp(pi/16) q0,q2;
}

gate mcphase_140054432591824(param0) q0,q1,q2 {
  cp(pi/32) q1,q2;
  cx q1,q0;
  cp(-pi/32) q0,q2;
  cx q1,q0;
  cp(pi/32) q0,q2;
}

gate mcphase_140054432590992(param0) q0,q1,q2 {
  cp(pi/4) q1,q2;
  cx q1,q0;
  cp(-pi/4) q0,q2;
  cx q1,q0;
  cp(pi/4) q0,q2;
}

gate mcphase_140054432593616(param0) q0,q1,q2 {
  cp(pi/8) q1,q2;
  cx q1,q0;
  cp(-pi/8) q0,q2;
  cx q1,q0;
  cp(pi/8) q0,q2;
}

gate mcphase_140054432582416(param0) q0,q1,q2 {
  cp(pi/16) q1,q2;
  cx q1,q0;
  cp(-pi/16) q0,q2;
  cx q1,q0;
  cp(pi/16) q0,q2;
}

gate mcphase_140056001448144(param0) q0,q1,q2 {
  cp(pi/4) q1,q2;
  cx q1,q0;
  cp(-pi/4) q0,q2;
  cx q1,q0;
  cp(pi/4) q0,q2;
}

gate mcphase_140056001445968(param0) q0,q1,q2 {
  cp(pi/8) q1,q2;
  cx q1,q0;
  cp(-pi/8) q0,q2;
  cx q1,q0;
  cp(pi/8) q0,q2;
}

gate mcphase_140056001447120(param0) q0,q1,q2 {
  cp(pi/16) q1,q2;
  cx q1,q0;
  cp(-pi/16) q0,q2;
  cx q1,q0;
  cp(pi/16) q0,q2;
}

gate mcphase_140056001449168(param0) q0,q1,q2 {
  cp(pi/4) q1,q2;
  cx q1,q0;
  cp(-pi/4) q0,q2;
  cx q1,q0;
  cp(pi/4) q0,q2;
}

gate mcphase_140056001448272(param0) q0,q1,q2 {
  cp(pi/8) q1,q2;
  cx q1,q0;
  cp(-pi/8) q0,q2;
  cx q1,q0;
  cp(pi/8) q0,q2;
}

gate mcphase_140056001449552(param0) q0,q1,q2 {
  cp(pi/4) q1,q2;
  cx q1,q0;
  cp(-pi/4) q0,q2;
  cx q1,q0;
  cp(pi/4) q0,q2;
}

gate qft8_dg_dg q0,q1,q2,q3,q4,q5,q6,q7 {
  h q0;
  cp(-pi/2) q1,q0;
  h q1;
  cp(-pi/4) q2,q0;
  cp(-pi/2) q2,q1;
  h q2;
  cp(-pi/8) q3,q0;
  cp(-pi/4) q3,q1;
  cp(-pi/2) q3,q2;
  h q3;
  cp(-pi/16) q4,q0;
  cp(-pi/8) q4,q1;
  cp(-pi/4) q4,q2;
  cp(-pi/2) q4,q3;
  h q4;
  cp(-pi/32) q5,q0;
  cp(-pi/16) q5,q1;
  cp(-pi/8) q5,q2;
  cp(-pi/4) q5,q3;
  cp(-pi/2) q5,q4;
  h q5;
  cp(-pi/64) q6,q0;
  cp(-pi/32) q6,q1;
  cp(-pi/16) q6,q2;
  cp(-pi/8) q6,q3;
  cp(-pi/4) q6,q4;
  cp(-pi/2) q6,q5;
  h q6;
  cp(-pi/128) q7,q0;
  cp(-pi/64) q7,q1;
  cp(-pi/32) q7,q2;
  cp(-pi/16) q7,q3;
  cp(-pi/8) q7,q4;
  cp(-pi/4) q7,q5;
  cp(-pi/2) q7,q6;
  h q7;
}

gate arithmetic_power q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11 {
  h q4;
  h q5;
  h q6;
  h q7;
  h q8;
  h q9;
  h q10;
  h q11;
  cp(pi) q0,q4;
  cp(pi/2) q0,q5;
  cp(pi/4) q0,q6;
  cp(pi/8) q0,q7;
  cp(pi/16) q0,q8;
  cp(pi/32) q0,q9;
  cp(pi/64) q0,q10;
  cp(pi/128) q0,q11;
  mcphase(pi) q0,q1,q6;
  mcphase_140054432585424(pi/2) q0,q1,q7;
  mcphase_140054432591248(pi/4) q0,q1,q8;
  mcphase_140054432581584(pi/8) q0,q1,q9;
  mcphase_140054432587792(pi/16) q0,q1,q10;
  mcphase_140054432590928(pi/32) q0,q1,q11;
  mcphase(pi) q0,q2,q7;
  mcphase_140054432590736(pi/2) q0,q2,q8;
  mcphase_140054432590160(pi/4) q0,q2,q9;
  mcphase_140054432585488(pi/8) q0,q2,q10;
  mcphase_140054432591824(pi/16) q0,q2,q11;
  mcphase(pi) q0,q3,q8;
  mcphase_140054432590992(pi/2) q0,q3,q9;
  mcphase_140054432593616(pi/4) q0,q3,q10;
  mcphase_140054432582416(pi/8) q0,q3,q11;
  cp(pi) q1,q6;
  cp(pi/2) q1,q7;
  cp(pi/4) q1,q8;
  cp(pi/8) q1,q9;
  cp(pi/16) q1,q10;
  cp(pi/32) q1,q11;
  mcphase(pi) q1,q2,q8;
  mcphase_140056001448144(pi/2) q1,q2,q9;
  mcphase_140056001445968(pi/4) q1,q2,q10;
  mcphase_140056001447120(pi/8) q1,q2,q11;
  mcphase(pi) q1,q3,q9;
  mcphase_140056001449168(pi/2) q1,q3,q10;
  mcphase_140056001448272(pi/4) q1,q3,q11;
  cp(pi) q2,q8;
  cp(pi/2) q2,q9;
  cp(pi/4) q2,q10;
  cp(pi/8) q2,q11;
  mcphase(pi) q2,q3,q10;
  mcphase_140056001449552(pi/2) q2,q3,q11;
  cp(pi) q3,q10;
  cp(pi/2) q3,q11;
  qft8_dg_dg q4,q5,q6,q7,q8,q9,q10,q11;
}

gate arithmetic_adder_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15 {
  cx q8,q0;
  cx q8,q15;
  ccx q15,q0,q8;
  cx q9,q1;
  cx q9,q8;
  ccx q8,q1,q9;
  cx q10,q2;
  cx q10,q9;
  ccx q9,q2,q10;
  cx q11,q3;
  cx q11,q10;
  ccx q10,q3,q11;
  cx q12,q4;
  cx q12,q11;
  ccx q11,q4,q12;
  cx q13,q5;
  cx q13,q12;
  ccx q12,q5,q13;
  cx q14,q6;
  cx q14,q13;
  ccx q13,q6,q14;
  cx q14,q7;
  ccx q13,q6,q14;
  cx q14,q13;
  cx q13,q6;
  ccx q12,q5,q13;
  cx q13,q12;
  cx q12,q5;
  ccx q11,q4,q12;
  cx q12,q11;
  cx q11,q4;
  ccx q10,q3,q11;
  cx q11,q10;
  cx q10,q3;
  ccx q9,q2,q10;
  cx q10,q9;
  cx q9,q2;
  ccx q8,q1,q9;
  cx q9,q8;
  cx q8,q1;
  ccx q15,q0,q8;
  cx q8,q15;
  cx q15,q0;
}

gate arithmetic_adder_1 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16 {
  x q8;
  cx q8,q0;
  cx q8,q16;
  ccx q16,q0,q8;
  ccx q8,q1,q9;
  ccx q9,q2,q10;
  ccx q10,q3,q11;
  ccx q11,q4,q12;
  ccx q12,q5,q13;
  ccx q13,q6,q14;
  cx q14,q7;
  ccx q13,q6,q14;
  cx q14,q13;
  cx q13,q6;
  ccx q12,q5,q13;
  cx q13,q12;
  cx q12,q5;
  ccx q11,q4,q12;
  cx q12,q11;
  cx q11,q4;
  ccx q10,q3,q11;
  cx q11,q10;
  cx q10,q3;
  ccx q9,q2,q10;
  cx q10,q9;
  cx q9,q2;
  ccx q8,q1,q9;
  cx q9,q8;
  cx q8,q1;
  ccx q16,q0,q8;
  cx q8,q16;
  cx q16,q0;
  x q8;
}

gate main_arithmetic q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20 {
  arithmetic_power q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11;
  arithmetic_adder_0 q4,q5,q6,q7,q8,q9,q10,q11,q0,q1,q2,q3,q12,q13,q14,q15;
  arithmetic_adder_1 q4,q5,q6,q7,q8,q9,q10,q11,q16,q17,q18,q19,q20,q12,q13,q14,q15;
}

qreg q[21];
main_identity q[0],q[1],q[2],q[3];
main_hadamard_transform q[0],q[1],q[2],q[3];
main_arithmetic q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20];
