// Generated by Classiq.
// Classiq version: 0.46.1
// Creation timestamp: 2024-09-26T06:22:05.579430+00:00
// Random seed: 2248478024

OPENQASM 2.0;
include "qelib1.inc";
gate mcx_hybrid_gray_code_maslov15_140580864385488 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140580864385488_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140580864385488 q0,q1;
  x q0;
}

gate statepreparation_1_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140580864385488_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140580788230224 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140580788230224_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140580788230224 q0,q1;
  x q0;
}

gate statepreparation_1_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140580788230224_o0 q0,q1;
}

gate statepreparation_1_rygate_0_qinverse q0,q1 {
  ry(-0.6154797086703874) q0;
  statepreparation_1_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(0.6154797086703874) q0;
  statepreparation_1_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate lcu_controllers_inplace_prepare_int_5 q0,q1 {
  x q0;
}

gate mcx_140580760204688 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_140580760202640 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_140580760199248 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate ccswap_140580760202896 q0,q1,q2,q3 {
  mcx_140580760199248 q0,q1,q2,q3;
  mcx_140580760202640 q0,q1,q3,q2;
  mcx_140580760204688 q0,q1,q2,q3;
}

gate mcphase_140580762087120(param0) q0,q1,q2 {
  cp(0) q1,q2;
  cx q1,q0;
  cp(0) q0,q2;
  cx q1,q0;
  cp(0) q0,q2;
}

gate mcphase_140580762078608(param0) q0,q1,q2 {
  cp(pi/2) q1,q2;
  cx q1,q0;
  cp(-pi/2) q0,q2;
  cx q1,q0;
  cp(pi/2) q0,q2;
}

gate cch_140580762082000 q0,q1,q2 {
  mcphase_140580762078608(pi) q0,q1,q2;
  ry(pi/4) q2;
  ccx q0,q1,q2;
  ry(-pi/4) q2;
  ccx q0,q1,q2;
  mcphase_140580762087120(0) q0,q1,q2;
}

gate mcphase_140580762075920(param0) q0,q1,q2,q3 {
  cp(-pi/8) q2,q3;
  cx q2,q1;
  cp(pi/8) q1,q3;
  cx q2,q1;
  cp(-pi/8) q1,q3;
  cx q1,q0;
  cp(pi/8) q0,q3;
  cx q2,q0;
  cp(-pi/8) q0,q3;
  cx q1,q0;
  cp(pi/8) q0,q3;
  cx q2,q0;
  cp(-pi/8) q0,q3;
}

gate cciteration_expanded___18_dg q0,q1,q2,q3 {
  mcphase_140580762075920(-pi/2) q0,q1,q3,q2;
  cch_140580762082000 q0,q1,q2;
}

gate mcphase_140580762090832(param0) q0,q1,q2 {
  cp(0) q1,q2;
  cx q1,q0;
  cp(0) q0,q2;
  cx q1,q0;
  cp(0) q0,q2;
}

gate mcphase_140580762081232(param0) q0,q1,q2 {
  cp(pi/2) q1,q2;
  cx q1,q0;
  cp(-pi/2) q0,q2;
  cx q1,q0;
  cp(pi/2) q0,q2;
}

gate cch_140580762085840 q0,q1,q2 {
  mcphase_140580762081232(pi) q0,q1,q2;
  ry(pi/4) q2;
  ccx q0,q1,q2;
  ry(-pi/4) q2;
  ccx q0,q1,q2;
  mcphase_140580762090832(0) q0,q1,q2;
}

gate ccqft_no_swap_expanded___20_dg q0,q1,q2,q3 {
  cch_140580762085840 q0,q1,q3;
  cciteration_expanded___18_dg q0,q1,q2,q3;
}

gate ccqft_expanded___21_dg q0,q1,q2,q3 {
  ccqft_no_swap_expanded___20_dg q0,q1,q2,q3;
  ccswap_140580760202896 q0,q1,q2,q3;
}

gate lcu_controllers_qft_1 q0,q1,q2,q3 {
  ccqft_expanded___21_dg q0,q1,q2,q3;
}

gate lcu_controllers_inplace_prepare_int_4 q0,q1 {
  x q0;
}

gate lcu_controllers_inplace_prepare_int_3 q0,q1 {
  x q1;
}

gate mcphase_140581329931792(param0) q0,q1,q2 {
  cp(0) q1,q2;
  cx q1,q0;
  cp(0) q0,q2;
  cx q1,q0;
  cp(0) q0,q2;
}

gate mcphase_140581329935312(param0) q0,q1,q2 {
  cp(pi/2) q1,q2;
  cx q1,q0;
  cp(-pi/2) q0,q2;
  cx q1,q0;
  cp(pi/2) q0,q2;
}

gate cch_140581329928528 q0,q1,q2 {
  mcphase_140581329935312(pi) q0,q1,q2;
  ry(pi/4) q2;
  ccx q0,q1,q2;
  ry(-pi/4) q2;
  ccx q0,q1,q2;
  mcphase_140581329931792(0) q0,q1,q2;
}

gate mcphase_140581329930768(param0) q0,q1,q2,q3 {
  cp(pi/8) q2,q3;
  cx q2,q1;
  cp(-pi/8) q1,q3;
  cx q2,q1;
  cp(pi/8) q1,q3;
  cx q1,q0;
  cp(-pi/8) q0,q3;
  cx q2,q0;
  cp(pi/8) q0,q3;
  cx q1,q0;
  cp(-pi/8) q0,q3;
  cx q2,q0;
  cp(pi/8) q0,q3;
}

gate mcphase_140581329929808(param0) q0,q1,q2 {
  cp(0) q1,q2;
  cx q1,q0;
  cp(0) q0,q2;
  cx q1,q0;
  cp(0) q0,q2;
}

gate mcphase(param0) q0,q1,q2 {
  cp(pi/2) q1,q2;
  cx q1,q0;
  cp(-pi/2) q0,q2;
  cx q1,q0;
  cp(pi/2) q0,q2;
}

gate cch q0,q1,q2 {
  mcphase(pi) q0,q1,q2;
  ry(pi/4) q2;
  ccx q0,q1,q2;
  ry(-pi/4) q2;
  ccx q0,q1,q2;
  mcphase_140581329929808(0) q0,q1,q2;
}

gate cciteration_expanded___10 q0,q1,q2,q3 {
  cch q0,q1,q2;
  mcphase_140581329930768(pi/2) q0,q1,q3,q2;
}

gate ccqft_no_swap_expanded___12 q0,q1,q2,q3 {
  cciteration_expanded___10 q0,q1,q2,q3;
  cch_140581329928528 q0,q1,q3;
}

gate mcx_140580739546512 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_140580739541136 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate ccswap q0,q1,q2,q3 {
  mcx q0,q1,q2,q3;
  mcx_140580739541136 q0,q1,q3,q2;
  mcx_140580739546512 q0,q1,q2,q3;
}

gate ccqft_expanded___13 q0,q1,q2,q3 {
  ccswap q0,q1,q2,q3;
  ccqft_no_swap_expanded___12 q0,q1,q2,q3;
}

gate lcu_controllers_qft_0 q0,q1,q2,q3 {
  ccqft_expanded___13 q0,q1,q2,q3;
}

gate lcu_controllers_inplace_prepare_int_2 q0,q1 {
  x q1;
}

gate lcu_controllers_inplace_prepare_int_1 q0,q1 {
  x q1;
  x q0;
}

gate ccapply_to_all_expanded___5 q0,q1,q2,q3 {
}

gate lcu_controllers_apply_to_all q0,q1,q2,q3 {
  ccapply_to_all_expanded___5 q0,q1,q2,q3;
}

gate lcu_controllers_inplace_prepare_int_0 q0,q1 {
  x q0;
  x q1;
}

gate mcx_hybrid_gray_code_maslov15 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15 q0,q1;
  x q0;
}

gate statepreparation_0_rygate_1_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate statepreparation_0_rygate_1 q0,q1 {
  statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(-0.6154797086703874) q0;
  statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(0.6154797086703874) q0;
}

gate main_statepreparation_0 q0,q1 {
  ry(pi/3) q1;
  statepreparation_0_rygate_1 q0,q1;
}

gate main_lcu_controllers q0,q1,q2,q3 {
  lcu_controllers_inplace_prepare_int_0 q2,q3;
  lcu_controllers_apply_to_all q2,q3,q0,q1;
  lcu_controllers_inplace_prepare_int_1 q2,q3;
  lcu_controllers_inplace_prepare_int_2 q2,q3;
  lcu_controllers_qft_0 q2,q3,q0,q1;
  lcu_controllers_inplace_prepare_int_3 q2,q3;
  lcu_controllers_inplace_prepare_int_4 q2,q3;
  lcu_controllers_qft_1 q2,q3,q0,q1;
  lcu_controllers_inplace_prepare_int_5 q2,q3;
}

gate main_statepreparation_1 q0,q1 {
  statepreparation_1_rygate_0_qinverse q0,q1;
  ry(-pi/3) q1;
}

qreg q[4];
main_statepreparation_0 q[2],q[3];
main_lcu_controllers q[0],q[1],q[2],q[3];
main_statepreparation_1 q[2],q[3];
